spring:
  application:
    name: community

  datasource:
    url: jdbc:mysql://localhost:3306/community_db
    username: root
    password: devil
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
